import '@ant-design/v5-patch-for-react-19';
import type { Metadata } from "next";
import "./globals.css";
import "./font.css";
import "./style.css";
import QueryProvider from "./components/QueryProvider";
import { ConfigProvider, App } from "antd";
import appTheme from "./theme";
import { AuthProvider } from "@/context/AuthContext";
// import ShamsiMonths from '@/constance/ShamsiMonths';
import dayjs from 'dayjs'
import jalaliday from 'jalaliday'
import locale from 'antd/locale/fa_IR';
import 'dayjs/locale/fa';

dayjs.extend(jalaliday);
dayjs().calendar('jalali').locale('fa').format('YYYY/MM/DD')

const farsiMonthsLocale = locale;
// farsiMonthsLocale.DatePicker.lang.shortMonths = ShamsiMonths;



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <div className="container">
          <QueryProvider>
            <AuthProvider>
              <ConfigProvider direction="rtl" theme={appTheme} locale={farsiMonthsLocale}>
                <App>
                  {children}
                </App>
              </ConfigProvider>
            </AuthProvider>
          </QueryProvider>
        </div>
      </body>
    </html>
  );
}
