import '@ant-design/v5-patch-for-react-19';
import type { Metadata } from "next";
import "./globals.css";
import "./font.css";
import "./style.css";
import QueryProvider from "./components/QueryProvider";
import { ConfigProvider, App } from "antd";
import appTheme from "./theme";
import { AuthProvider } from "@/context/AuthContext";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <div className="container">
          <QueryProvider>
            <AuthProvider>
              <ConfigProvider direction="rtl" theme={appTheme}>
                <App>
                  {children}
                </App>
              </ConfigProvider>
            </AuthProvider>
          </QueryProvider>
        </div>
      </body>
    </html>
  );
}
