import type { Metadata } from "next";
import "./globals.css";
import "./font.css";
import "./style.css";
import QueryProvider from "./components/QueryProvider";
import { ConfigProvider } from "antd";
import appTheme from "./theme";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className="">
        <div className="container">
          <QueryProvider>
            <ConfigProvider direction="rtl" theme={appTheme}>
              {children}
            </ConfigProvider>
          </QueryProvider>
        </div>
      </body>
    </html>
  );
}
